# Generated by Django 3.1.4 on 2021-02-06 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0006_auto_20210206_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazon',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 6, 16, 56, 32, 812059)),
        ),
    ]
