# Generated by Django 3.1.4 on 2021-02-05 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0002_auto_20210129_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebay',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 5, 21, 4, 50, 241915)),
        ),
    ]
